---
deployment:
  tasks:
    - export DEPLOYPATH=/home/baniabg/public_html/emptycanvas/home
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH